// Generated by CoffeeScript 1.10.0
(function() {
  var Overlay, Popper, js, limit, overlay, queer, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  js = {};

  queer = {};

  overlay = null;

  limit = 0;

  js.boot = function() {
    limit = $('#limit');
    return 1;
  };

  js.mstats = function() {
    var delta, fps;
    queer.stats = $('<div id="stats">');
    fps = $('<div>fps: <div class="value" id="fps">0</div></div>');
    delta = $('<div>delta: <div class="value" id="delta">0</div></div>');
    queer.stats.append(fps);
    queer.stats.append(delta);
    $('#limit').append(queer.stats);
    queer.fps = $('#fps');
    queer.delta = $('#delta');
    return 0;
  };

  js.second = function() {
    queer.fps.html(app.fps);
    queer.delta.html(app.delta);
    return 0;
  };

  js.overlay = function() {
    root.overlay = overlay = new Overlay;
    if (typeof app !== "undefined" && app !== null) {
      app.overlay = overlay;
    }
    return 1;
  };

  Overlay = (function() {
    function Overlay() {
      this.build();
    }

    Overlay.prototype.build = function() {
      limit.append((this.shipping = new Popper()).popper);
      return 1;
    };

    return Overlay;

  })();

  Popper = (function() {
    function Popper() {
      this.popper = $('<div class="popper">creative menu</div>');
    }

    return Popper;

  })();

  root.Overlay = Overlay;

  root.js = js;

}).call(this);
